name: PR filter v1

# Controls when the workflow will run
on:
  pull_request:
    on: [opened, reopened]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      # Fetch the lastest commits from the remote repository (all branches)
      - run: git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
      - run: |
          ####  TARGET CONFIGURATION  ####
          script_target="https://raw.githubusercontent.com/penguinencounter/FTC_prfilter/main/.github/workflows/detect_and_diff.sh"
          ################################

          echo "Downloading script from $script_target"
          wget -O /tmp/detect_diff.sh $script_target
          echo "Granting permissions"
          chmod +x /tmp/detect_diff.sh
      # Run aforementioned script
      - run: |
          if [ "$(bash /tmp/detect_diff.sh)" ]; then
            changed=true
            echo YEEAH
          else
            echo Nope
          fi
      
      # And write a comment (TODO add checks)
      # - uses: actions/github-script@v6
      #   with:
        #     github-token: ${{secrets.GITHUB_TOKEN}}
        #     script: |
        #       console.log(context.payload)
        #       console.log({
        #         issue_number: context.payload.pull_request.number,
        #         owner: context.payload.repository.owner.login,
        #         repo: context.payload.repository.name,
        #         body: "HEWWO!"
        #       })
        #       github.rest.issues.createComment({
        #         issue_number: context.payload.pull_request.number,
        #         owner: context.payload.repository.owner.login,
        #         repo: context.payload.repository.name,
        #         body: "HEWWO!"
        #       })
        