name: PR filter v1

# Controls when the workflow will run
on:
  pull_request:
    on: [opened]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  combined:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Only apply on testing and official repositories. (this file is inherited by forks, don't run on those)
    if: github.repository == 'penguinencounter/FTC_prfilter' || github.repository == 'FIRST-Tech-Challenge/FtcRobotController'
    # if: github.repository == 'FIRST-Tech-Challenge/FtcRobotController'

    steps:
      - uses: actions/checkout@v3
      # Fetch the lastest commits from the remote repository (all branches)
      - run: git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
      - name: download script
        if: false  # Use this to turn on/off downloading the script.
        run: |
          ####  TARGET CONFIGURATION (switch this to your own repo)  ####
          script_target="https://raw.githubusercontent.com/penguinencounter/FTC_prfilter/main/.github/workflows/generate_diff.sh"
          ###############################################################

          echo "Downloading script from $script_target"
          wget -O /tmp/generate_diff.sh $script_target
          echo "Granting permissions"
          chmod +x /tmp/generate_diff.sh
      - name: copy script from repo location
        if: true  # Use this to turn on/off retrieving the script from the repository.
        run: |
          # Copy the script from the repository to the workspace.
          echo "Copying script from repository"
          cp $GITHUB_WORKSPACE/.github/workflows/generate_diff.sh /tmp/generate_diff.sh
      # Run aforementioned script
      - name: output
        run: |
          ##################### CONFIGURE MESSAGE HERE #####################
          blocked_message="Hello! It looks like you're trying to merge your team's code into the *official FTC repository*. You probably don't want to do this, so we've closed your PR. If this is wrong, you can reopen it using the button below."
          warning_message="Hello! This repository doesn't accept PRs for code. You can keep this PR open to discuss the code or issues, but your code won't be merged."

          token=${{secrets.GITHUB_TOKEN}}
          if [ "$(bash /tmp/generate_diff.sh)" ]; then
            echo "PR matches target criteria"
            echo "https://api.github.com/repos/${{github.event.repository.owner.login}}/${{github.event.repository.name}}/issues/${{github.event.pull_request.number}}/comments"
            
            # Post a comment
            curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token $token" -d "{"\""body"\"":"\""$blocked_message"\""}" 'https://api.github.com/repos/${{github.event.repository.owner.login}}/${{github.event.repository.name}}/issues/${{github.event.pull_request.number}}/comments'

            # Close the PR
            curl -X PATCH -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $token" -d '{"state":"closed"}' 'https://api.github.com/repos/${{github.event.repository.owner.login}}/${{github.event.repository.name}}/issues/${{github.event.pull_request.number}}'
          else
            echo "PR did not match criteria (ok) sending warn message"
            curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token $token" -d "{"\""body"\"":"\""$blocked_message"\""}" 'https://api.github.com/repos/${{github.event.repository.owner.login}}/${{github.event.repository.name}}/issues/${{github.event.pull_request.number}}/comments'
          fi
        