name: PR filter v1

# Controls when the workflow will run
on:
  pull_request:
    on: [opened, reopened]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  combined:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Only apply on testing and official repositories. (this file is inherited by forks, don't run on those)
    if: github.repository == 'penguinencounter/FTC_prfilter' || github.repository == 'FIRST-Tech-Challenge/FtcRobotController'

    steps:
      - uses: actions/checkout@v3
      # Fetch the lastest commits from the remote repository (all branches)
      - run: git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
      - run: |
          ####  TARGET CONFIGURATION  ####
          script_target="https://raw.githubusercontent.com/penguinencounter/FTC_prfilter/main/.github/workflows/detect_and_diff.sh"
          ################################

          echo "Downloading script from $script_target"
          wget -O /tmp/detect_diff.sh $script_target
          echo "Granting permissions"
          chmod +x /tmp/detect_diff.sh
      # Run aforementioned script
      - name: output
        run: |
          token=${{secrets.GITHUB_TOKEN}}
          if [ "$(bash /tmp/detect_diff.sh)" ]; then
            echo "PR matches target criteria"
            echo "https://api.github.com/repos/${{github.event.repository.owner.login}}/${{github.event.repository.name}}/issues/${{github.event.pull_request.number}}/comments"
            # GITHUB API SHENANIGANS
            curl \
              -X POST \
              -H "Accept: application/vnd.github+json" \ 
              -H "Authorization: token $token" \
              "https://api.github.com/repos/${{github.event.repository.owner.login}}/${{github.event.repository.name}}/issues/${{github.event.pull_request.number}}/comments" \
              -d '{"body":"Fwagaga"}'
          else
            echo "PR did not match criteria"
          fi
        