name: PR filter v1

# Controls when the workflow will run
on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # And write a comment (TODO add checks)
      - uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log("hi I exist")
            console.log(context.payload)
            github.rest.issues.createComment({
              issueNumber: context.payload.pullrequest.number,
              owner: context.payload.repository.owner,
              repo: context.payload.repository.fullName,
              "HEWWO!"
            })
